# Generated by Django 4.2.2 on 2023-06-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='condition',
            field=models.CharField(choices=[('novo-sim', 'Novo SIM'), ('reuso-sim', 'Reutilizar')], default='novo-sim', max_length=15),
        ),
    ]
