# Generated by Django 4.2.2 on 2023-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_order_status_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AT', 'Ativado'), ('CC', 'Cancelado'), ('RB', 'Reembolsado'), ('RP', 'Reprocessar'), ('PR', 'Processando'), ('VS', 'Verificar SIM')], default='PR', max_length=20),
        ),
    ]
