# Generated by Django 4.2.2 on 2023-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AT', 'Ativado'), ('CC', 'Cancelado'), ('RB', 'Reembolsado'), ('RP', 'Reprocessar'), ('PR', 'Processando'), ('VS', 'Verificar SIM'), ('AS', 'Atribuir SIM'), ('RT', 'Retirada'), ('MB', 'Motoboy'), ('AE', 'Agd. Envio')], default='PR', max_length=20),
        ),
    ]
