# Generated by Django 4.2.2 on 2023-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_order_status_alter_orders_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='type_sim',
            field=models.CharField(blank=True, default='sim', max_length=4, null=True),
        ),
    ]
