# Generated by Django 4.2.2 on 2023-07-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_email_orders_type_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chip-internacional-eua', 'USA'), ('chip-internacional-eua-e-canada', 'USA/CANADA'), ('chip-internacional-europa', 'EUROPA'), ('chip-internacional-global', 'GLOBAL')], max_length=50),
        ),
    ]
