# Generated by Django 4.2.2 on 2023-08-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_alter_sims_sim'),
        ('orders', '0012_alter_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cell_eid',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cell_imei',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cell_mod',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.sims'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ord_chip_nun',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
