# Generated by Django 4.2.2 on 2023-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orders_tracking_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cell_mod',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
