# Generated by Django 4.2.2 on 2023-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orders_cell_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AG', 'Agência'), ('AS', 'Atribuir SIM'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('MB', 'Motoboy'), ('PR', 'Processando'), ('RE', 'Reembolsar'), ('RB', 'Reembolsado'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RT', 'Retirada'), ('VS', 'Verificar SIM')], default='PR', max_length=20),
        ),
    ]
