# Generated by Django 4.2.2 on 2023-08-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_orders_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
