# Generated by Django 4.2.2 on 2023-08-25 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_alter_orders_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['id'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='id_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_notes', to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
