# Generated by Django 4.2.2 on 2023-08-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_notes_options_remove_notes_id_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-id'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
    ]
