# Generated by Django 4.2.2 on 2023-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ord_chip_nun',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
