# Generated by Django 4.2.2 on 2023-09-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_notes_type_note_alter_notes_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='type_note',
            field=models.CharField(choices=[('S', 'Sistema'), ('P', 'Privada')], default=None, max_length=1),
        ),
    ]
