# Generated by Django 4.2.2 on 2023-09-26 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0027_alter_notes_type_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='type_note',
            field=models.CharField(choices=[('S', 'Sistema'), ('P', 'Privada')], default='S', max_length=1),
        ),
    ]
