# Generated by Django 4.2.2 on 2023-09-26 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0028_alter_notes_id_user_alter_notes_type_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
