# Generated by Django 4.2.2 on 2023-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_notes_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB'), ('1gb', '1GB'), ('2gb', '2GB'), ('ilimitado', 'Ilimitado')], max_length=15),
        ),
    ]
