version: '3'

services:
  web:
    build: .
    command: /djangoapp/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - "8080:80"