version: '3.8'

services:
  web:
    build: .
    command: /djangoapp/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot