# Generated by Django 4.2.2 on 2023-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_alter_sims_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='sim_status',
            field=models.CharField(choices=[('DS', 'Disponível'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('TC', 'Troca')], default='DS', max_length=20),
        ),
    ]
